### ISSUE TITLE
assert vcdId not in self.idcode2series

### ISSUE THREAD

**Issue by sioan** [Nic30/pyDigitalWaveTools#10]
Getting the error when trying to parse attached vcd file ( renamed txt for uploading)

~~`python scripts/vcd2json.py xsim_dump.vcd 
Traceback (most recent call last):
  File "scripts/vcd2json.py", line 4, in <module>
    from pyDigitalWaveTools.vcd.parser import VcdParser
ImportError: No module named pyDigitalWaveTools.vcd.parser`~~

Apologies, wrong error message above.  See one below

`sioan@sioan-Millennium$ python scripts/vcd2json.py ./xsim_dump.vcd 
Traceback (most recent call last):
  File "scripts/vcd2json.py", line 14, in <module>
    vcd.parse(vcd_file)
  File "/home/sioan/Desktop/repositories/pyDigitalWaveTools/pyDigitalWaveTools/vcd/parser.py", line 142, in parse
    self.keyword_dispatch[token[1]](tokeniser, token[1])
  File "/home/sioan/Desktop/repositories/pyDigitalWaveTools/pyDigitalWaveTools/vcd/parser.py", line 231, in vcd_var
    assert vcdId not in self.idcode2series
AssertionError
(venv) `

[xsim_dump.txt](https://github.com/Nic30/pyDigitalWaveTools/files/6896440/xsim_dump.txt)

**Comment by Nic30** [comment]
Hello, 

from looking at files in package https://pypi.org/project/pyDigitalWaveTools/1.1/#files
it seems that the mentioned module is present.

```
python scripts/vcd2json.py xsim_dump.vcd Traceback (most recent call last): File "scripts/vcd2json.py", line 4, in <module> from pyDigitalWaveTools.vcd.parser import VcdParser ImportError: No module named pyDigitalWaveTools.vcd.parser
```
if possible use virtualenv  or install the package.

> `assert vcdId not in self.idcode2series`

Should be fixed, can you minify the vcd to be < 50KB, (you can delete everything except two clocks with vcd id 'T' and keep just several updates for this variable). We need some minimal example for tests.

**Comment by Nic30** [comment]
Also if possible please keep 1 issue per github issue. problem with imports seems to be a different issue than the title.
About that, can you describe how did you install  pyDigitalWaveTools or where it is so we can resolve this problem with incorrect
`PYTHONPATH`?

**Comment by sioan** [comment]
Apologies, wrong error message.  Yes, there's a venv and it's been installed via pip.

`sioan@sioan-Millennium$ python scripts/vcd2json.py ./xsim_dump.vcd 
Traceback (most recent call last):
  File "scripts/vcd2json.py", line 14, in <module>
    vcd.parse(vcd_file)
  File "/home/sioan/Desktop/repositories/pyDigitalWaveTools/pyDigitalWaveTools/vcd/parser.py", line 142, in parse
    self.keyword_dispatch[token[1]](tokeniser, token[1])
  File "/home/sioan/Desktop/repositories/pyDigitalWaveTools/pyDigitalWaveTools/vcd/parser.py", line 231, in vcd_var
    assert vcdId not in self.idcode2series
AssertionError`

**Comment by Nic30** [comment]
Did you actually activate the virtualenv?

> /home/sioan/Desktop/repositories/pyDigitalWaveTools/pyDigitalWaveTools/vcd/parser.py

This path does not look like a virtualenv, it looks like a manually downloaded repository.
See an example installation which I did just try. Note that `(venv) ` after the virtualenv is activated and installation directly from git.
(You must `git pull` in your git folder ` /home/sioan/Desktop/repositories/pyDigitalWaveTools/` or install directly from git using command bellow.)

```
nic30@nic30-Precision-5530:~$ virtualenv venv
created virtual environment CPython3.8.10.final.0-64 in 238ms
  creator CPython3Posix(dest=/home/nic30/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/nic30/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

nic30@nic30-Precision-5530:~$ source venv/bin/activate

(venv) nic30@nic30-Precision-5530:~$ pip install git+git://github.com/Nic30/pyDigitalWaveTools#egg=pyDigitalWaveTools  --upgrade --no-cache
Collecting git+git://github.com/Nic30/pyDigitalWaveTools
  Cloning git://github.com/Nic30/pyDigitalWaveTools to /tmp/pip-req-build-w9hk784b
  Running command git clone -q git://github.com/Nic30/pyDigitalWaveTools /tmp/pip-req-build-w9hk784b
Building wheels for collected packages: pyDigitalWaveTools
  Building wheel for pyDigitalWaveTools (setup.py) ... done
  Created wheel for pyDigitalWaveTools: filename=pyDigitalWaveTools-1.1-py3-none-any.whl size=13184 sha256=d7eacfc62e0aa5176ea19d901429a95b4c58966afc270a0b071fc1795e893765
  Stored in directory: /tmp/pip-ephem-wheel-cache-xeg22fio/wheels/8f/fb/59/4eca4d7263c68077e33266739859207952f11ba8bff8fc8f5e
Successfully built pyDigitalWaveTools
Installing collected packages: pyDigitalWaveTools
Successfully installed pyDigitalWaveTools-1.1
```

Also if you have the folder with the same name in current path it will interfere with the python package.

**Comment by sioan** [comment]
Yes, yes, the venv has been activated
`source venv/bin/venv` 

There's no import error, that was a copy paste mistake on my part.  See corrected trace back above

Both the pip pypi version and the editable install show this error.
I'm currently working with the editable pip install

`pip install -e . ` 

In order to debug.
Currently stepping through the code with IPython.embed() and will send a PR once it's debugged.  Does the attached `xsim_dump.txt ` work for you?

**Comment by Nic30** [comment]
> Does the attached xsim_dump.txt work for you?

Yes, i fixed it today in https://github.com/Nic30/pyDigitalWaveTools/commit/bae19c2d20e23a592b3f0677cdf9e8608952d8d8

**Comment by sioan** [comment]
Nice!  Thank you!

**Comment by SaintNicholas** [comment]
Hey @Nic30, I wanted to double check to see if this change was working as intended.

In this change, vcdId was changed to be `Union[str, VcdVarInfo]`. In my experience though, vcdId is either being set to a string (the ID) or else the series of time/values for the ID, but it's not being set to VcdVarInfo.

`self.idcode2series.get(vcdId, None)` returns the time/values for the ID, and that's being set to the vcdId field, is that intended?

**Comment by Nic30** [comment]
@SaintNicholas  Can you provide some example so I can see it?

**Comment by SaintNicholas** [comment]
Sample VCD:

```
$date
	Wed Jun 16 21:25:39 2021
$end
$version
	Placeholder
$end
$timescale
	1ps
$end
$scope module top $end
$var wire 1 * signal1 $end
$var wire 1 # signal2 $end
$var wire 1 * signal3 $end
$enddefinitions $end
#0
0*
0#
#1
1*
1#
#2
1*
0#
```

Sample Driver:
```
from pyDigitalWaveTools.vcd.parser import *

with open("debug.vcd", "r") as vcd_file:
    vcd = VcdParser()
    vcd.parse(vcd_file)

    # The scope, for use when looking at a signal.
    scope = ""
    # A simple DFS to visit all nodes.
    nodes = [vcd.scope]
    while len(nodes):
        node = nodes.pop(0)

        if isinstance(node, VcdVarScope):
            nodes = list(node.children.values()) + nodes
            scope = node._getDebugName()
        elif isinstance(node, VcdVarParsingInfo):
            full_signal_name = scope + "." + node.name
            if full_signal_name:
                print(full_signal_name)
                print(f"VcdVarParsingInfo.vcdId type: {type(node.vcdId)}  {node.vcdId}")
                print()
        else:
            print(f"Unknown type {type(node)}")
```

Output:
```
root.top.signal1
VcdVarParsingInfo.vcdId type: <class 'str'>  *

root.top.signal2
VcdVarParsingInfo.vcdId type: <class 'str'>  #

root.top.signal3
VcdVarParsingInfo.vcdId type: <class 'list'>  [(0, '0'), (1, '1'), (2, '1')]
```

vcdId in code is `vcdId: Union[str, VcdVarInfo]`. In my sample VCD file, there are 2 signals with the same vcdId (*), so I would expect the vcdId of `root.top.signal3` to be a `VcdVarInfo` pointing to `root.top.signal1`, but instead it's a list of time/value tuples.
