### ISSUE TITLE
String argument parser needed

### ISSUE THREAD

**Issue by raczben** [Nic30/pyDigitalWaveTools#4]
I recommend adding a new feature.

As I understand [`VcdParser.parse()`][1] accepts file handler only, however, I want to give a string to it. It would be nice if it can accept a vcd content as a string.

[1]:    https://github.com/Nic30/pyDigitalWaveTools/blob/7a2e96e09437c53c1305c783f82e6adba5a8c032/pyDigitalWaveTools/vcd/parser.py#L86

**Comment by Nic30** [comment]
Hello, maybe the name file_handle gives the impression that it needs to be file so I added an extra function for the string
